### ISSUE TITLE
Exclude feature not removing devices

### ISSUE THREAD

**Issue by Adelgiorno92** [mickgiles/homebridge-vesync#16]
I have several VeSync devices but use this plugin only for simple smart plugs. There is a purifier and a humidifier in my account that have their own plugins that better support the functions but I can't remove those two from being added as basic on/off accessories even when using the Exclude feature. The air purifier is a ESW01-USA (Core 200S) and the Humidifier is the Classic 300S (Ultrasonic Smart Humidifier). 

I've added the following to the Exclude list but they both still show: ESW01-USA,ESW01,CORE200S,200S,CLASSIC300S,300S

**Comment by mickgiles** [comment]
I have the Core200S and have to add both Core200S and ESW01-USA to exclude it. Also note that this is case sensitive so it must be Core200S and not CORE200S.
You can always see the model to exclude by going to the gear icon in the device you want to exlude in the homebridge accessories section and copy/paste what is listed there under "Model"

**Comment by Adelgiorno92** [comment]
I was able to get the air purifier removed but I still can't get the humidifier to be removed. This is the model I have: https://us.vesync.com/product-detail/17?utm_source=GG&gclid=CjwKCAiAqt-dBhBcEiwATw-ggISXLSFe4K-FQQsqpwRMsWjhRSqUMZQ6V5HJiSGIlrNdZXmWINr02hoCEq0QAvD_BwE

This is all the models I've tried listing:
ESW01-USA,esw01,200S,Core200S,300S,classic300s,core200s,classic300,Classic300s,LUH-A601S-WUSB,Classic 300S

 The listing of the accessory itself:
![image](https://user-images.githubusercontent.com/122118831/211086423-a5b2e688-59dc-4ee4-b854-42c3f99625df.jpeg)

**Comment by Adelgiorno92** [comment]
I added one more "Classic300S" and that seemed to work even though the model listed wasn't that in the Accessory Details.
