### ISSUE TITLE
Bulbs should not appear in this 

### ISSUE THREAD

**Issue by adityasalapaka** [mickgiles/homebridge-vesync#2]
My Etekcity lightbulb (https://www.amazon.com/Etekcity-Dimmable-Equivalent-2700K-6500K-Required/dp/B07NR514SD/ref=sr_1_3?dchild=1&keywords=etekcity+light+bulb&qid=1606044189&sr=8-3) shows up here but it shouldn't. Its probably appearing as part of the API pull which just lists all devices. The home app also shows the device but as an outlet and toggling it doesn't work. Is it possible to create an exclusionary list (possibly as part of the config file) to prevent these devices from appearing in the home app?

**Comment by mickgiles** [comment]
I've added support to turn on/off those bulbs but no other features. 
I've also added the feature you suggested; an exclusion list configuration to exclude devices from showing up at all.
