### ISSUE TITLE
I have a Leviot LV-PUR131S airpurifier...

### ISSUE THREAD

**Issue by romeomont** [mickgiles/homebridge-vesync#6]
I was hoping to be able to use this with my air purifier but i have no idea if this is available with this. The vesync2 homebridge plugin has no syntax guide for the purifier. Any help would be appreciated. Thanks.

**Comment by sdavisNL** [comment]
Would also really love for this to be added!

**Comment by mickgiles** [comment]
I added basic on/off support for this unit however I cannot test it as I don't own one. Let me know if it works.

**Comment by sdavisNL** [comment]
> I added basic on/off support for this unit however I cannot test it as I don't own one. Let me know if it works.

It works! Thanks so much!.

Is there a way to add support for the different modes (Off, Auto, Low, Medium, High) and the sensor? Even if you could point me to where you get the info to add to the plugin I could play around with it.

Again, thanks so much. Even the basic support you've given us is a win!

**Comment by mickgiles** [comment]
If you want to take a crack at it, I would look at this to understand how to talk to homebridge about an air purifier device
https://github.com/seikan/homebridge-mi-air-purifier/blob/master/index.js

and then I would look at this to understand the API for your specific device (this is where I got the API for the on/off fucntion)
https://github.com/webdjoe/pyvesync_v2/blob/master/src/pyvesync_v2/vesyncfan.py

If you get something working I'm happy to merge it in
