### ISSUE TITLE
Light Switches Missing

### ISSUE THREAD

**Issue by emtz1977** [mickgiles/homebridge-vesync#7]
Latest v2.2.0 of the code removed the light switches.  Rolled code back to v2.1.0 and they are back.  Can you confirm light switches are no longer supported?

**Comment by mickgiles** [comment]
just published a new version reverting back to original behavior. I cannot guarantee light work as I don't own any but at least now they won't be excluded

**Comment by emtz1977** [comment]
That fixed it.  Thank you
