### ISSUE TITLE
Two distinct outlets recognized, but both trigger the same single outlet

### ISSUE THREAD

**Issue by anderfrank** [mickgiles/homebridge-vesync#9]
I have two distinct Etekcity outlets in my Vesync app that are both working completely correct in the app (tapping each outlet listed turns on/off that outlet). However in Homebridge both outlets show up but clicking on either one activates the exact same outlet every time. The other outlet never turns on or off. 

I have tried uninstalling and cleaning up the plugin, rebooting Homebridge and reinstalling the plugin but get the same result. The homebridge logs for the plugin show it detects both outlets separately ( I see two different serial numbers) but both items on Homebridge only seem to trigger one of the two outlets.

**Comment by mickgiles** [comment]
Which model outlets do you have?

**Comment by anderfrank** [comment]
ESW01-USA
Etekcity Voltson Smart Wi-Fi outlet

**Comment by mickgiles** [comment]
That's very bizarre to me. I have a bunch of the ESW01-USA devices and have never seen this.
Can you try deleting them both from the Vesync App and then re-adding them back to it?

**Comment by anderfrank** [comment]
That did the trick. I should have tried that first but the fact that they worked in the app just fine held me up. Thanks for your assistance!

**Comment by mickgiles** [comment]
excellent!
